//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDRegist : DbContext
    {
        public BDRegist()
            : base("name=BDRegist")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Lechenia> Lechenia { get; set; }
        public virtual DbSet<Oplati> Oplati { get; set; }
        public virtual DbSet<Oslognenia> Oslognenia { get; set; }
        public virtual DbSet<Otcheta> Otcheta { get; set; }
        public virtual DbSet<PolisStrahovania> PolisStrahovania { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<Sotrydniki> Sotrydniki { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusOplati> StatusOplati { get; set; }
        public virtual DbSet<StrahSlychai> StrahSlychai { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<YchresdeniaLecheia> YchresdeniaLecheia { get; set; }
        public virtual DbSet<Yslugi> Yslugi { get; set; }
        public virtual DbSet<YslugiStrahSlysay> YslugiStrahSlysay { get; set; }
    }
}
