//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.PolisStrahovania = new HashSet<PolisStrahovania>();
        }
    
        public int IDClienta { get; set; }
        public string Imya { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<System.DateTime> DenRojdenia { get; set; }
        public string Adres { get; set; }
        public long NumberPhone { get; set; }
        public string Pochta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolisStrahovania> PolisStrahovania { get; set; }
    }
}
