//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lechenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lechenia()
        {
            this.Oslognenia = new HashSet<Oslognenia>();
        }
    
        public int IDLechenia { get; set; }
        public int IDStrahSlychai { get; set; }
        public int IDYchresdenia { get; set; }
        public Nullable<System.DateTime> DataNachalaLechenia { get; set; }
        public Nullable<System.DateTime> DateKoncaLechenia { get; set; }
    
        public virtual YchresdeniaLecheia YchresdeniaLecheia { get; set; }
        public virtual StrahSlychai StrahSlychai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oslognenia> Oslognenia { get; set; }
    }
}
