//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplati
    {
        public int IDOplati { get; set; }
        public int IDStatusOplati { get; set; }
        public int IDOtcheta { get; set; }
        public Nullable<decimal> SumOplati { get; set; }
        public Nullable<System.DateTime> DataOplati { get; set; }
    
        public virtual StatusOplati StatusOplati { get; set; }
        public virtual StrahSlychai StrahSlychai { get; set; }
    }
}
