//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oslognenia
    {
        public int IDOslognenia { get; set; }
        public int IDLechenia { get; set; }
        public string InforamtiaOslognenia { get; set; }
        public Nullable<System.DateTime> DataNachalaOslognenia { get; set; }
    
        public virtual Lechenia Lechenia { get; set; }
    }
}
