//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otcheta
    {
        public int IDOtcheta { get; set; }
        public int IDYslugi { get; set; }
        public Nullable<System.DateTime> DataNapicaniaOtcheta { get; set; }
        public string OpisanieOtcheta { get; set; }
    
        public virtual Yslugi Yslugi { get; set; }
    }
}
