//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolisStrahovania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolisStrahovania()
        {
            this.StrahSlychai = new HashSet<StrahSlychai>();
        }
    
        public int IDPolisa { get; set; }
        public int IDClienta { get; set; }
        public long NumberPolis { get; set; }
        public Nullable<System.DateTime> DateNachalaDestvia { get; set; }
        public Nullable<System.DateTime> DateKoncaDestvia { get; set; }
        public decimal StrahovaySumma { get; set; }
        public string TipPolisa { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrahSlychai> StrahSlychai { get; set; }
    }
}
