//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovateli()
        {
            this.Sotrydniki = new HashSet<Sotrydniki>();
        }
    
        public int IDPolzovateliaDlyaAvtorizacii { get; set; }
        public int IDRoli { get; set; }
        public string Logini { get; set; }
        public string Paroli { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int TwoFactorAvtor { get; set; }
    
        public virtual Roli Roli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrydniki> Sotrydniki { get; set; }
    }
}
