//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rolki
    {
        public string NazvanieRoli { get; set; }
        public Nullable<int> IDRoli { get; set; }
        public string Imya { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public string NumberPhone { get; set; }
        public string Pochta { get; set; }
        public string SeriaPasporta { get; set; }
        public string NomerPasporta { get; set; }
    }
}
