//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrydniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrydniki()
        {
            this.StrahSlychai = new HashSet<StrahSlychai>();
        }
    
        public int IDSotrydnika { get; set; }
        public Nullable<int> IDPolzovateliaDlyaAvtorizacii { get; set; }
        public Nullable<int> IDRoli { get; set; }
        public string Imya { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public string NumberPhone { get; set; }
        public string Pochta { get; set; }
        public string SeriaPasporta { get; set; }
        public string NomerPasporta { get; set; }
    
        public virtual Polzovateli Polzovateli { get; set; }
        public virtual Roli Roli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrahSlychai> StrahSlychai { get; set; }
    }
}
