//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrahSlychai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StrahSlychai()
        {
            this.Lechenia = new HashSet<Lechenia>();
            this.Oplati = new HashSet<Oplati>();
            this.YslugiStrahSlysay = new HashSet<YslugiStrahSlysay>();
        }
    
        public int IDStrahSlychai { get; set; }
        public int IDStatusa { get; set; }
        public int IDPolisa { get; set; }
        public Nullable<int> IDStatusOplati { get; set; }
        public Nullable<int> IDSotrydnika { get; set; }
        public Nullable<System.DateTime> DataOtpravkiZayavki { get; set; }
        public string OpisanieStrahSlychai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lechenia> Lechenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oplati> Oplati { get; set; }
        public virtual PolisStrahovania PolisStrahovania { get; set; }
        public virtual Sotrydniki Sotrydniki { get; set; }
        public virtual Status Status { get; set; }
        public virtual StatusOplati StatusOplati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YslugiStrahSlysay> YslugiStrahSlysay { get; set; }
    }
}
