//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallofregist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YslugiStrahSlysay
    {
        public int IDYslugiStrahSlysay { get; set; }
        public int IDStrahSlychai { get; set; }
        public int IDYslugi { get; set; }
    
        public virtual StrahSlychai StrahSlychai { get; set; }
        public virtual Yslugi Yslugi { get; set; }
    }
}
